// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/kafka.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProduceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceRequest) Reset() {
	*x = ProduceRequest{}
	mi := &file_proto_kafka_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceRequest) ProtoMessage() {}

func (x *ProduceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kafka_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceRequest.ProtoReflect.Descriptor instead.
func (*ProduceRequest) Descriptor() ([]byte, []int) {
	return file_proto_kafka_proto_rawDescGZIP(), []int{0}
}

func (x *ProduceRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ProduceRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ProduceRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ProduceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     int32                  `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceResponse) Reset() {
	*x = ProduceResponse{}
	mi := &file_proto_kafka_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceResponse) ProtoMessage() {}

func (x *ProduceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kafka_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceResponse.ProtoReflect.Descriptor instead.
func (*ProduceResponse) Descriptor() ([]byte, []int) {
	return file_proto_kafka_proto_rawDescGZIP(), []int{1}
}

func (x *ProduceResponse) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *ProduceResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,3,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset        int64                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	MaxMessages   int32                  `protobuf:"varint,5,opt,name=max_messages,json=maxMessages,proto3" json:"max_messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_proto_kafka_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kafka_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_proto_kafka_proto_rawDescGZIP(), []int{2}
}

func (x *FetchRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *FetchRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *FetchRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *FetchRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FetchRequest) GetMaxMessages() int32 {
	if x != nil {
		return x.MaxMessages
	}
	return 0
}

type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*MessageProto        `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_proto_kafka_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kafka_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_proto_kafka_proto_rawDescGZIP(), []int{3}
}

func (x *FetchResponse) GetMessages() []*MessageProto {
	if x != nil {
		return x.Messages
	}
	return nil
}

type MessageProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageProto) Reset() {
	*x = MessageProto{}
	mi := &file_proto_kafka_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageProto) ProtoMessage() {}

func (x *MessageProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kafka_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageProto.ProtoReflect.Descriptor instead.
func (*MessageProto) Descriptor() ([]byte, []int) {
	return file_proto_kafka_proto_rawDescGZIP(), []int{4}
}

func (x *MessageProto) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *MessageProto) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MessageProto) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *MessageProto) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,3,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset        int64                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_proto_kafka_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kafka_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_proto_kafka_proto_rawDescGZIP(), []int{5}
}

func (x *CommitRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *CommitRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CommitRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *CommitRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_proto_kafka_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kafka_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_proto_kafka_proto_rawDescGZIP(), []int{6}
}

func (x *CommitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type JoinGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	ConsumerId    string                 `protobuf:"bytes,3,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGroupRequest) Reset() {
	*x = JoinGroupRequest{}
	mi := &file_proto_kafka_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupRequest) ProtoMessage() {}

func (x *JoinGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kafka_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupRequest.ProtoReflect.Descriptor instead.
func (*JoinGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_kafka_proto_rawDescGZIP(), []int{7}
}

func (x *JoinGroupRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *JoinGroupRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *JoinGroupRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

type JoinGroupResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AssignedPartitions []int32                `protobuf:"varint,1,rep,packed,name=assigned_partitions,json=assignedPartitions,proto3" json:"assigned_partitions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *JoinGroupResponse) Reset() {
	*x = JoinGroupResponse{}
	mi := &file_proto_kafka_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupResponse) ProtoMessage() {}

func (x *JoinGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kafka_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupResponse.ProtoReflect.Descriptor instead.
func (*JoinGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_kafka_proto_rawDescGZIP(), []int{8}
}

func (x *JoinGroupResponse) GetAssignedPartitions() []int32 {
	if x != nil {
		return x.AssignedPartitions
	}
	return nil
}

var File_proto_kafka_proto protoreflect.FileDescriptor

const file_proto_kafka_proto_rawDesc = "" +
	"\n" +
	"\x11proto/kafka.proto\x12\tminikafka\"N\n" +
	"\x0eProduceRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"G\n" +
	"\x0fProduceResponse\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\x05R\tpartition\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"\x93\x01\n" +
	"\fFetchRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x03 \x01(\x05R\tpartition\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\x12!\n" +
	"\fmax_messages\x18\x05 \x01(\x05R\vmaxMessages\"D\n" +
	"\rFetchResponse\x123\n" +
	"\bmessages\x18\x01 \x03(\v2\x17.minikafka.MessageProtoR\bmessages\"l\n" +
	"\fMessageProto\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"q\n" +
	"\rCommitRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x03 \x01(\x05R\tpartition\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\"*\n" +
	"\x0eCommitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"_\n" +
	"\x10JoinGroupRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1f\n" +
	"\vconsumer_id\x18\x03 \x01(\tR\n" +
	"consumerId\"D\n" +
	"\x11JoinGroupResponse\x12/\n" +
	"\x13assigned_partitions\x18\x01 \x03(\x05R\x12assignedPartitions2\x8d\x02\n" +
	"\x06Broker\x12@\n" +
	"\aProduce\x12\x19.minikafka.ProduceRequest\x1a\x1a.minikafka.ProduceResponse\x12:\n" +
	"\x05Fetch\x12\x17.minikafka.FetchRequest\x1a\x18.minikafka.FetchResponse\x12=\n" +
	"\x06Commit\x12\x18.minikafka.CommitRequest\x1a\x19.minikafka.CommitResponse\x12F\n" +
	"\tJoinGroup\x12\x1b.minikafka.JoinGroupRequest\x1a\x1c.minikafka.JoinGroupResponseB)Z'github.com/parkheejha10/minikafka/protob\x06proto3"

var (
	file_proto_kafka_proto_rawDescOnce sync.Once
	file_proto_kafka_proto_rawDescData []byte
)

func file_proto_kafka_proto_rawDescGZIP() []byte {
	file_proto_kafka_proto_rawDescOnce.Do(func() {
		file_proto_kafka_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kafka_proto_rawDesc), len(file_proto_kafka_proto_rawDesc)))
	})
	return file_proto_kafka_proto_rawDescData
}

var file_proto_kafka_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_kafka_proto_goTypes = []any{
	(*ProduceRequest)(nil),    // 0: minikafka.ProduceRequest
	(*ProduceResponse)(nil),   // 1: minikafka.ProduceResponse
	(*FetchRequest)(nil),      // 2: minikafka.FetchRequest
	(*FetchResponse)(nil),     // 3: minikafka.FetchResponse
	(*MessageProto)(nil),      // 4: minikafka.MessageProto
	(*CommitRequest)(nil),     // 5: minikafka.CommitRequest
	(*CommitResponse)(nil),    // 6: minikafka.CommitResponse
	(*JoinGroupRequest)(nil),  // 7: minikafka.JoinGroupRequest
	(*JoinGroupResponse)(nil), // 8: minikafka.JoinGroupResponse
}
var file_proto_kafka_proto_depIdxs = []int32{
	4, // 0: minikafka.FetchResponse.messages:type_name -> minikafka.MessageProto
	0, // 1: minikafka.Broker.Produce:input_type -> minikafka.ProduceRequest
	2, // 2: minikafka.Broker.Fetch:input_type -> minikafka.FetchRequest
	5, // 3: minikafka.Broker.Commit:input_type -> minikafka.CommitRequest
	7, // 4: minikafka.Broker.JoinGroup:input_type -> minikafka.JoinGroupRequest
	1, // 5: minikafka.Broker.Produce:output_type -> minikafka.ProduceResponse
	3, // 6: minikafka.Broker.Fetch:output_type -> minikafka.FetchResponse
	6, // 7: minikafka.Broker.Commit:output_type -> minikafka.CommitResponse
	8, // 8: minikafka.Broker.JoinGroup:output_type -> minikafka.JoinGroupResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_kafka_proto_init() }
func file_proto_kafka_proto_init() {
	if File_proto_kafka_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kafka_proto_rawDesc), len(file_proto_kafka_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kafka_proto_goTypes,
		DependencyIndexes: file_proto_kafka_proto_depIdxs,
		MessageInfos:      file_proto_kafka_proto_msgTypes,
	}.Build()
	File_proto_kafka_proto = out.File
	file_proto_kafka_proto_goTypes = nil
	file_proto_kafka_proto_depIdxs = nil
}
